<?php
echo "                        ";
if ( $_GET['flash'] )
{
    if ( $infos_webradio['flux_flash'] )
    {
        echo $infos_webradio['flux_flash'];
    }
    else
    {
        if ( $infos_webradio['webradio_typeserveur'] == "Shoutcast" )
        {
            echo "<object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0\" width=\"250\" height=\"50\" id=\"player\" align=\"middle\">\r\n                                <param name=\"allowScriptAccess\" value=\"sameDomain\" />\r\n                                \r\n                        <param name=\"flashvars\" value=\"urlshoutcast=".$infos_webradio['webradio_serveur_ip']."&portshoutcast=".$infos_webradio['webradio_serveur_port']."&xmll=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Shoutcast/".$infos_webradio['webradio_serveur_ip']."_".$infos_webradio['webradio_serveur_port'].".xml&folderurl=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Shoutcast\" />\r\n                                \r\n                                <param name=\"wmode\" value=\"transparent\"> \r\n                                <param name=\"movie\" value=\"../includes/plugins/webradios/player/Shoutcast/player.swf\" /><param name=\"menu\" value=\"false\" /><param name=\"quality\" value=\"high\" /><param name=\"bgcolor\" value=\"#333333\" /><embed src=\"../includes/plugins/webradios/player/Shoutcast/player.swf\" menu=\"false\" quality=\"high\" bgcolor=\"#333333\" width=\"250\" height=\"50\" name=\"player\" align=\"middle\" allowScriptAccess=\"sameDomain\" type=\"application/x-shockwave-flash\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" wmode=\"transparent\"  flashvars=\"urlshoutcast=".$infos_webradio['webradio_serveur_ip']."&portshoutcast=".$infos_webradio['webradio_serveur_port']."&xmll=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Shoutcast/".$infos_webradio['webradio_serveur_ip']."_".$infos_webradio['webradio_serveur_port'].".xml&folderurl=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Shoutcast\" />\r\n                                </object>";
        }
        else
        {
            if ( $infos_webradio['webradio_typeserveur'] == "Autre" )
            {
                echo "\r\n                                    <object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0\" width=\"250\" height=\"50\" id=\"player\" align=\"middle\">\r\n                                <param name=\"allowScriptAccess\" value=\"sameDomain\" />\r\n                                \r\n                        <param name=\"flashvars\" value=\"urlshoutcast=".$infos_webradio['webradio_serveur_ip']."&portshoutcast=".$infos_webradio['webradio_serveur_port']."&xmll=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Autre/".$infos_webradio['webradio_serveur_ip']."_".$infos_webradio['webradio_serveur_port'].".xml&folderurl=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Autre\" />\r\n                                \r\n                                <param name=\"wmode\" value=\"transparent\"> \r\n                                <param name=\"movie\" value=\"../includes/plugins/webradios/player/Autre/player.swf\" /><param name=\"menu\" value=\"false\" /><param name=\"quality\" value=\"high\" /><param name=\"bgcolor\" value=\"#333333\" /><embed src=\"../includes/plugins/webradios/player/Autre/player.swf\" menu=\"false\" quality=\"high\" bgcolor=\"#333333\" width=\"250\" height=\"50\" name=\"player\" align=\"middle\" allowScriptAccess=\"sameDomain\" type=\"application/x-shockwave-flash\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" wmode=\"transparent\"  flashvars=\"urlshoutcast=".$infos_webradio['webradio_serveur_ip']."&portshoutcast=".$infos_webradio['webradio_serveur_port']."&xmll=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Autre/".$infos_webradio['webradio_serveur_ip']."_".$infos_webradio['webradio_serveur_port'].".xml&folderurl=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Autre\" />\r\n                                </object>\t\r\n                        ";
            }
            else
            {
                if ( $infos_webradio['webradio_typeserveur'] == "Icecast" )
                {
                    echo "\r\n                                    \r\n                        <object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0\" width=\"450\" height=\"40\" id=\"player\" align=\"middle\">\r\n                        <param name=\"allowScriptAccess\" value=\"sameDomain\" />\r\n                        \r\n                        <param name=\"flashvars\" value=\"xmll=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Icecast/".$infos_webradio['webradio_serveur_ip']."_".$infos_webradio['icecast_mount_point'].".xml\" />\r\n                                <param name=\"wmode\" value=\"transparent\"> \r\n                        \r\n                        <param name=\"movie\" value=\"../includes/plugins/webradios/player/Icecast/player.swf\" /><param name=\"menu\" value=\"false\" /><param name=\"quality\" value=\"high\" /><embed src=\"../includes/plugins/webradios/player/Icecast/player.swf\" menu=\"false\" quality=\"high\"  width=\"450\" height=\"40\" name=\"player\" align=\"middle\" allowScriptAccess=\"sameDomain\" type=\"application/x-shockwave-flash\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" flashvars=\"xmll=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Icecast/".$infos_webradio['webradio_serveur_ip']."_".$infos_webradio['icecast_mount_point'].".xml\" wmode=\"transparent\" />\r\n                        </object>\t\t\r\n                        ";
                }
                else
                {
                    if ( $infos_webradio['webradio_typeserveur'] == "Radionomy" )
                    {
                        echo "\r\n                                    <object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0\" width=\"250\" height=\"70\" id=\"player\" align=\"middle\">\r\n                        <param name=\"allowScriptAccess\" value=\"sameDomain\" />\r\n                        \r\n                        <param name=\"flashvars\" value=\"xmll=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Radionomy/".$infos_webradio['webradio_serveur_ip']."_".$infos_webradio['icecast_mount_point'].".xml\" />\r\n                                <param name=\"wmode\" value=\"transparent\"> \r\n                        \r\n                        <param name=\"movie\" value=\"../includes/plugins/webradios/player/Radionomy/player.swf\" /><param name=\"menu\" value=\"false\" /><param name=\"quality\" value=\"high\" /><embed src=\"../includes/plugins/webradios/player/Radionomy/player.swf\" menu=\"false\" quality=\"high\"  width=\"250\" height=\"70\" name=\"player\" align=\"middle\" allowScriptAccess=\"sameDomain\" type=\"application/x-shockwave-flash\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" flashvars=\"xmll=http://".$_SERVER['HTTP_HOST']."/includes/plugins/webradios/player/Radionomy/".$infos_webradio['webradio_serveur_ip']."_".$infos_webradio['icecast_mount_point'].".xml\" wmode=\"transparent\" />\r\n                        </object>\t\r\n                        \r\n                        \r\n                        ";
                    }
                }
            }
        }
    }
}
else
{
    echo "\r\n                        <object id=\"lecteur2\" height=\"46\" width=\"445\" classid =\"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" codebase =\" http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=5,1,52,701\" standby=\"Loading ...\" type=\"application/x-oleobject\">\r\n                                        <param name=\"Filename\" value=\"".$infos_webradio['flux_windows']."\" />\r\n                                        <param name=\"animationatStart\" value=\"true\" />\r\n                                        <param name=\"transparentatStart\" value=\"true\" />\r\n                                        <param name=\"autoStart\" value=\"true\" />\r\n                        \r\n                                        <param name=\"showControls\" value=\"true\" />\r\n                                        <embed width=\"445\" height=\"46\" hidden=\"False\" autostart=\"True\" loop=\"True\" type=\"application/x-mplayer2\" pluginspage=\"http://www.microsoft.com/Windows/MediaPlayer/download/default.asp\" src=\"".$infos_webradio['flux_windows']."\" id=\"lecteur2\"> </embed>\r\n                                      </object>\r\n                        ";
}
?>
