<?php
@session_start( );
header( "Content-Type: text/html; charset=iso-8859-1" );
@ini_set( "display_errors", "Off" );
error_reporting( 0 );
include( $_SERVER['DOCUMENT_ROOT']."/includes/plugins/webradios/onair/Icecast/appel.php" );
$titre = $_SESSION['titreencours'];
echo "<s";
echo "pan >";
echo $titre;
echo "</span><br />\r\n\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"http://";
echo $_SERVER['HTTP_HOST'];
echo "/ressources/templates/ultimate_rouge/js/jquery/jquery.js\"></script>\r\n\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"http://";
echo $_SERVER['HTTP_HOST'];
echo "/includes/plugins/webradios/onair/Icecast/vote/javascript/jquery.simplemodal.js\"></script>\r\n";
echo "<s";
echo "cript type=\"text/javascript\" src=\"http://";
echo $_SERVER['HTTP_HOST'];
echo "/includes/plugins/webradios/onair/Icecast/vote/javascript/init.js\"></script>\r\n<link type='text/css' href='http://";
echo $_SERVER['HTTP_HOST'];
echo "/includes/plugins/webradios/onair/Icecast/vote/style/stylesheet.css' rel='stylesheet' media='screen' />\r\n<link type='text/css' href='http://";
echo $_SERVER['HTTP_HOST'];
echo "/includes/plugins/webradios/onair/Icecast/vote/style/basic.css' rel='stylesheet' media='screen' />\r\n\r\n";
echo "<s";
echo "tyle>\r\nform { float:left; }\r\n</style>\r\n\r\n\t\t\t<div id=\"action_vote\">\t\r\n\t\t\t<div id=\"login_response\"></div>\r\n\r\n\t\t\t<form class=\"clearfixslide\" method=\"post\" id=\"login\" action=\"javascript:alert('success!');\">\r\n\t\t\t\t\t<input type=\"image\" src=\"http://";
echo $_SERVER['HTTP_HOST'];
echo "/ressources/medias/vote/voterpour.png\" />\r\n\t\t\t\t\t<input type=\"hidden\" value=\"pour\" name=\"voter\">\r\n\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"action_vote\">\r\n\t\t\t\t\t<input type=\"hidden\" name=\"webradio_id\" value=\"";
echo urlencode( $_GET['webradio_id'] );
echo "\">\r\n\t\t\t\t\t<input type=\"hidden\" name=\"titre\" value=\"";
echo htmlentities( $titre );
echo "\">\r\n\t\t\t</form>\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t<form class=\"clearfixslide\" method=\"post\" id=\"login\" action=\"javascript:alert('success!');\">\r\n\t\t\t\t\t<input type=\"image\" src=\"http://";
echo $_SERVER['HTTP_HOST'];
echo "/ressources/medias/vote/votercontre.png\" />\r\n\t\t\t\t\t<input type=\"hidden\" value=\"contre\" name=\"voter\">\r\n\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"action_vote\">\r\n\t\t\t\t\t<input type=\"hidden\" name=\"webradio_id\" value=\"";
echo urlencode( $_GET['webradio_id'] );
echo "\">\r\n\t\t\t\t\t<input type=\"hidden\" name=\"titre\" value=\"";
echo htmlentities( $titre );
echo "\">\r\n\t\t\t</form>\r\n</div>\t\r\n";
?>
